jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: RITURAJ-1-1_MASTER1
    type: runSh
    steps:
      - IN: dv-man
      - IN: dv-image
      - TASK:
        - script: echo "here"
        
