jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: infra-provision-long-long-very-long-name-to-test
    type: runSh
    steps:
      - IN: dv-man
      - TASK:
        - script: echo "here"
        
