jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: RITURAJ-1-1_MASTER1_need-to-test-seperator_for_then_to_work
    type: runSh
    steps:
      - IN: dv-man
      - IN: dv-image
      - TASK:
        - script: echo "here"
        
