vars:
  master: 
    sourceName1: library/nginx
    sourceName2: library/nginx
    branch: master
 
  rc: 
    sourceName1: library/redis
    sourceName2: library/redis
    branch: rc
  
  region: us-west-2   
  sourceName1: library/nginx
  integration: ship_int

jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-2
        branch: ${branch}
      - IN: sample_nodejs_runCI
    on_success:
      NOTIFY: slack_notification_master
        
 
  - name: sample_nodejs_runCI
    type: runCI
    steps:
      - IN: rituraj-1-1
        branch: rc
