jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: RITURAJ-1-1_MASTER1_need-to-test-seriously-we-need-to-test-at-any-cost-seperator_for_then_to_work_seperator_for_then_to_work_seperator_for_then_to_work
    type: runSh
    steps:
      - IN: dv-man
      - IN: dv-image
      - IN: dv-image-new
      - IN: dv-image-new2
      - TASK:
        - script: echo "here"
        
